#:schema node_modules/wrangler/config-schema.json
name = "yousef-shtiwe-ai"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-15"
pages_build_output_dir = "./build/client"
send_metrics = false

# Environment variables (these should be set in Cloudflare dashboard)
[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT = "production"

[env.preview.vars]
NODE_ENV = "development"
ENVIRONMENT = "preview"

# Note: For Cloudflare Pages, custom headers should be defined in the built output (or project) as a `_headers` file.
# The project already contains `public/_headers` which Pages will use.