#:schema node_modules/wrangler/config-schema.json
name = "yousef-shtiwe-ai"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-15"
pages_build_output_dir = "./build/client"
send_metrics = false

# Environment variables (these should be set in Cloudflare dashboard)
[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT = "production"

[env.preview.vars]
NODE_ENV = "development"
ENVIRONMENT = "preview"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Headers configuration
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "public, max-age=0, s-maxage=86400"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/favicon*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/yousef-logo*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"