#:schema node_modules/wrangler/config-schema.json
name = "yousef-shtiwe-ai"
compatibility_date = "2025-01-15"
pages_build_output_dir = "./build/client"
compatibility_flags = ["nodejs_compat"]
send_metrics = false

# Environment variables (set these in Cloudflare dashboard)
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "development"

# Notes:
# - [build] and routes are not supported in Cloudflare Pages wrangler.toml and have been removed.
# - Functions routing is handled automatically by Pages Functions directory structure.
